version: '3.3'

services:
  app:
    build: .
    command: python app.py
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - error.json:/app/error.json
  mongodb:
    image: mongo:latest
    restart: always
    container_name: 'mongodb'
    volumes:
      - mongodb_volume:/data/db
volumes:
  mongodb_volume: