version: '3.7'

services:
  app:
    build: .
    command: python app.py
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command:
      - 'redis-server'
      - '--save 60 1'
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
volumes:
  redis_data: