version: '3.3'

services:
  app:
    build: .
    command: python app.py
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    container_name: 'mongodb'
    volumes:
      - mongodb_volume:/data/db
volumes:
  mongodb_volume: